export const GET_ERRORS = "GET_ERRORS";

// Profile user
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const USER_REQUEST = "USER_REQUEST";
export const USER_CREATED = "USER_CREATED";
export const FORGOT_USER = "FORGOT_USER";
export const RESET_USER = "RESET_USER";

export const CHANGE_USERNAME = "CHANGE_USERNAME";

// MonMovies
export const GET_MONMOVIES = "GET_MONMOVIES";
export const GET_CLOSEUP_MONMOVIE = "GET_CLOSEUP_MONMOVIE";
export const POST_MONMOVIE = "POST_MONMOVIE";
export const DELETE_MONMOVIE = "DELETE_MONMOVIE";
export const UPDATE_MONMOVIE = "UPDATE_MONMOVIE";

// Booking
export const COMPLETE_BOOKING = "COMPLETE_BOOKING";
export const END_BOOKING_ON_SUCCESS = "END_BOOKING_ON_SUCCESS";
export const UPDATE_BOOKING = "UPDATE_BOOKING";

export const ADMIN_PAGE_TRUE = "ADMIN_PAGE_TRUE";
export const ADMIN_PAGE_FALSE = "ADMIN_PAGE_FALSE";

export const CURRENT_CLOSE_UP_MOVIE_ID = "CURRENT_CLOSE_UP_MOVIE_ID";
export const REMOVE_CURRENT_CLOSE_UP_MOVIE_ID =
  "REMOVE_CURRENT_CLOSE_UP_MOVIE_ID";

// MoviesDB
export const GET_MOVIES = "GET_MOVIES";
export const MOVIE_POPUP = "MOVIE_POPUP";
export const MOVIE_POPUP_CLOSE = "MOVIE_POPUP_CLOSE";
export const SEARCH_MOVIE_TMDB = "SEARCH_MOVIE_TMDB";
export const IMDB_POPUP = "IMDB_POPUP";
export const IMDB_POPUP_CLOSE = "IMDB_POPUP_CLOSE";
export const MOVIE_ADDED_SUCCESS = "MOVIE_ADDED_SUCCESS";
export const DELETE_MOVIE_DB = "DELETE_MOVIE_DB";
export const UPDATE_MOVIE_DB = "UPDATE_MOVIE_DB";
export const GET_ARCHIVED_MOVIES = "GET_ARCHIVED_MOVIES";

//Users
export const GET_ALL_USERS = "GET_ALL_USERS";
export const USER_DELETE_DB = "USER_DELETE_DB";
export const USER_POPUP = "USER_POPUP";
export const USER_POPUP_CLOSE = "USER_POPUP_CLOSE";
export const RESET_USER_STATS = "RESET_USER_STATS";
export const USER_STATS_TO_ARCHIVE = "USER_STATS_TO_ARCHIVE";
export const USER_ARCHIVE = "USER_ARCHIVE";
export const UPDATE_USER = "UPDATE_USER";
