const salong_1 = [
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_3",
      seatNr: "1.3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_2",
      seatNr: "1.2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_1",
      seatNr: "1.1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r2s5",
      seatNr: "5",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r2s4",
      seatNr: "4",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r2s3",
      seatNr: "3",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r2s2",
      seatNr: "2",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r2s1",
      seatNr: "1",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s6",
      seatNr: "6",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s5",
      seatNr: "5",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s4",
      seatNr: "4",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s3",
      seatNr: "3",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s2",
      seatNr: "2",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r3s1",
      seatNr: "1",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ]
];

const salong_2 = [
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "extra_1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      seat: "r1s1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ]
];

module.exports = { salong_1, salong_2 };
