const salong_1 = [
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_3",
      seatNr: "1.3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_2",
      seatNr: "1.2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_1",
      seatNr: "1.1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r2s5",
      seatNr: "5",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r2s4",
      seatNr: "4",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r2s3",
      seatNr: "3",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r2s2",
      seatNr: "2",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r2s1",
      seatNr: "1",
      row: 2,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s6",
      seatNr: "6",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s5",
      seatNr: "5",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s4",
      seatNr: "4",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s3",
      seatNr: "3",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s2",
      seatNr: "2",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r3s1",
      seatNr: "1",
      row: 3,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ]
];

const salong_2 = [
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "extra_1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ],
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "r1s1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ]
];

////////
const event = [
  [
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "1",
      seatNr: "1",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "2",
      seatNr: "2",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "3",
      seatNr: "3",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "4",
      seatNr: "4",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "5",
      seatNr: "5",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "6",
      seatNr: "6",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "7",
      seatNr: "7",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },

    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "8",
      seatNr: "8",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "9",
      seatNr: "9",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "10",
      seatNr: "10",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "11",
      seatNr: "11",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "12",
      seatNr: "12",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },

    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "13",
      seatNr: "13",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "14",
      seatNr: "14",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "15",
      seatNr: "15",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "16",
      seatNr: "16",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "17",
      seatNr: "17",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "18",
      seatNr: "18",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "19",
      seatNr: "19",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "20",
      seatNr: "20",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "21",
      seatNr: "21",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "22",
      seatNr: "22",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "23",
      seatNr: "23",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "24",
      seatNr: "24",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "25",
      seatNr: "25",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "26",
      seatNr: "26",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "27",
      seatNr: "27",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "28",
      seatNr: "28",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "29",
      seatNr: "29",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    },
    {
      eventType: "",
      title: "",
      screeningDate: "",
      screeningTime: "",
      _id: "",
      poster: "poster_not_available.jpg",
      seat: "30",
      seatNr: "30",
      row: 1,
      booked: false,
      customer: "",
      responsible: { id: "" },
      vip: false
    }
  ]
];

module.exports = { salong_1, salong_2, event };
